language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit tests/ --coverage-clover=coverage.xml
# after_success:
#   - bash <(curl -s https://codecov.io/bash) -t <id>
